// <auto-generated />
using System;
using Infrastructure.Persistence.Tenants;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Tenants.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260912183311_InitialTenantAccess")]
    partial class InitialTenantAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Authorization.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f81cb90-d5a9-4c64-8b6f-a50378e81970"),
                            Code = "members.read",
                            Description = "View tenant members.",
                            Name = "View members"
                        },
                        new
                        {
                            Id = new Guid("1a7bd5bd-0e5f-42aa-b0d9-a8144ea96574"),
                            Code = "members.manage",
                            Description = "Add and remove tenant members.",
                            Name = "Manage members"
                        },
                        new
                        {
                            Id = new Guid("292c9f17-f4c3-48b9-b66a-8de6f2d1e5b0"),
                            Code = "roles.read",
                            Description = "View tenant roles and their permissions.",
                            Name = "View roles"
                        },
                        new
                        {
                            Id = new Guid("3c8c6534-6ca7-4b5f-93c5-1ba3c6d0a0b9"),
                            Code = "roles.manage",
                            Description = "Create and edit tenant roles.",
                            Name = "Manage roles"
                        },
                        new
                        {
                            Id = new Guid("4d1b2a8e-8cf1-41a2-9d57-e5123e4ca92f"),
                            Code = "invitations.manage",
                            Description = "Create and revoke tenant invitations.",
                            Name = "Manage invitations"
                        });
                });

            modelBuilder.Entity("Domain.Authorization.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8d5f5ca-1b85-4ca3-99d2-a8534c9dc124"),
                            Code = "owner",
                            Description = "Full access to this tenant.",
                            Name = "Owner"
                        },
                        new
                        {
                            Id = new Guid("5b2c1a44-9d3e-4f81-b0a7-6c8e2f95d310"),
                            Code = "member",
                            Description = "Read-only access to this tenant.",
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("Domain.Authorization.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("role_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId")
                        .IsUnique();

                    b.HasIndex("role_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("role_permissions", b =>
                {
                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("permission_id")
                        .HasColumnType("uuid");

                    b.HasKey("role_id", "permission_id");

                    b.HasIndex("permission_id");

                    b.ToTable("role_permissions");

                    b.HasData(
                        new
                        {
                            role_id = new Guid("e8d5f5ca-1b85-4ca3-99d2-a8534c9dc124"),
                            permission_id = new Guid("0f81cb90-d5a9-4c64-8b6f-a50378e81970")
                        },
                        new
                        {
                            role_id = new Guid("e8d5f5ca-1b85-4ca3-99d2-a8534c9dc124"),
                            permission_id = new Guid("1a7bd5bd-0e5f-42aa-b0d9-a8144ea96574")
                        },
                        new
                        {
                            role_id = new Guid("e8d5f5ca-1b85-4ca3-99d2-a8534c9dc124"),
                            permission_id = new Guid("292c9f17-f4c3-48b9-b66a-8de6f2d1e5b0")
                        },
                        new
                        {
                            role_id = new Guid("e8d5f5ca-1b85-4ca3-99d2-a8534c9dc124"),
                            permission_id = new Guid("3c8c6534-6ca7-4b5f-93c5-1ba3c6d0a0b9")
                        },
                        new
                        {
                            role_id = new Guid("e8d5f5ca-1b85-4ca3-99d2-a8534c9dc124"),
                            permission_id = new Guid("4d1b2a8e-8cf1-41a2-9d57-e5123e4ca92f")
                        },
                        new
                        {
                            role_id = new Guid("5b2c1a44-9d3e-4f81-b0a7-6c8e2f95d310"),
                            permission_id = new Guid("0f81cb90-d5a9-4c64-8b6f-a50378e81970")
                        },
                        new
                        {
                            role_id = new Guid("5b2c1a44-9d3e-4f81-b0a7-6c8e2f95d310"),
                            permission_id = new Guid("292c9f17-f4c3-48b9-b66a-8de6f2d1e5b0")
                        });
                });

            modelBuilder.Entity("Domain.Authorization.User", b =>
                {
                    b.HasOne("Domain.Authorization.Role", "Role")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("role_permissions", b =>
                {
                    b.HasOne("Domain.Authorization.Permission", null)
                        .WithMany()
                        .HasForeignKey("permission_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Authorization.Role", null)
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
