// <auto-generated />
using System;
using Infrastructure.Persistence.Tenants;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Tenants.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260909225351_SeedSystemAccessCatalog")]
    partial class SeedSystemAccessCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Access.Permissions.TenantPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0f81cb90-d5a9-4c64-8b6f-a50378e81970"),
                            Code = "members.read",
                            Description = "View tenant members.",
                            Name = "View members"
                        },
                        new
                        {
                            Id = new Guid("1a7bd5bd-0e5f-42aa-b0d9-a8144ea96574"),
                            Code = "members.manage",
                            Description = "Add and remove tenant members.",
                            Name = "Manage members"
                        },
                        new
                        {
                            Id = new Guid("292c9f17-f4c3-48b9-b66a-8de6f2d1e5b0"),
                            Code = "roles.read",
                            Description = "View tenant roles and their permissions.",
                            Name = "View roles"
                        },
                        new
                        {
                            Id = new Guid("3c8c6534-6ca7-4b5f-93c5-1ba3c6d0a0b9"),
                            Code = "roles.manage",
                            Description = "Create and edit tenant roles.",
                            Name = "Manage roles"
                        },
                        new
                        {
                            Id = new Guid("4d1b2a8e-8cf1-41a2-9d57-e5123e4ca92f"),
                            Code = "invitations.manage",
                            Description = "Create and revoke tenant invitations.",
                            Name = "Manage invitations"
                        });
                });

            modelBuilder.Entity("Domain.Access.Roles.TenantRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8d5f5ca-1b85-4ca3-99d2-a8534c9dc124"),
                            Code = "owner",
                            Description = "Full access to this tenant.",
                            Name = "Owner"
                        });
                });

            modelBuilder.Entity("Domain.Access.Roles.TenantRolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("e8d5f5ca-1b85-4ca3-99d2-a8534c9dc124"),
                            PermissionId = new Guid("0f81cb90-d5a9-4c64-8b6f-a50378e81970")
                        },
                        new
                        {
                            RoleId = new Guid("e8d5f5ca-1b85-4ca3-99d2-a8534c9dc124"),
                            PermissionId = new Guid("1a7bd5bd-0e5f-42aa-b0d9-a8144ea96574")
                        },
                        new
                        {
                            RoleId = new Guid("e8d5f5ca-1b85-4ca3-99d2-a8534c9dc124"),
                            PermissionId = new Guid("292c9f17-f4c3-48b9-b66a-8de6f2d1e5b0")
                        },
                        new
                        {
                            RoleId = new Guid("e8d5f5ca-1b85-4ca3-99d2-a8534c9dc124"),
                            PermissionId = new Guid("3c8c6534-6ca7-4b5f-93c5-1ba3c6d0a0b9")
                        },
                        new
                        {
                            RoleId = new Guid("e8d5f5ca-1b85-4ca3-99d2-a8534c9dc124"),
                            PermissionId = new Guid("4d1b2a8e-8cf1-41a2-9d57-e5123e4ca92f")
                        });
                });

            modelBuilder.Entity("Domain.Access.Users.TenantUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Access.Users.TenantUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Domain.Access.Roles.TenantRolePermission", b =>
                {
                    b.HasOne("Domain.Access.Permissions.TenantPermission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Access.Roles.TenantRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Access.Users.TenantUserRole", b =>
                {
                    b.HasOne("Domain.Access.Roles.TenantRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Access.Users.TenantUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
