<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ControlPlane.Application\ControlPlane.Application.csproj" />
    <ProjectReference Include="..\ControlPlane.Domain\ControlPlane.Domain.csproj" />
    <ProjectReference Include="..\ControlPlane.Contracts\ControlPlane.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

</Project>
