// <auto-generated />
using System;
using ControlPlane.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControlPlane.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20261010130837_SignUpTheOwnerLikeAnyUser")]
    partial class SignUpTheOwnerLikeAnyUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControlPlane.Application.Tenants.TenantOnboarding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeSpan>("CancellationTimeout")
                        .HasColumnType("interval")
                        .HasColumnName("cancellation_timeout");

                    b.Property<TimeSpan>("InvitationEmailTimeout")
                        .HasColumnType("interval")
                        .HasColumnName("invitation_email_timeout");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasDefaultValueSql("NULLIF(current_setting('app.tenant_id', true), '')::uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_tenant_onboardings");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_onboardings_tenant_id");

                    b.ToTable("tenant_onboardings", "catalog");
                });

            modelBuilder.Entity("ControlPlane.Domain.Invitations.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasDefaultValueSql("NULLIF(current_setting('app.tenant_id', true), '')::uuid");

                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.HasIndex("AcceptedBy")
                        .HasDatabaseName("ix_invitations_accepted_by");

                    b.HasIndex("InvitedBy")
                        .HasDatabaseName("ix_invitations_invited_by");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_invitations_role_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_invitations_tenant_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_invitations_token_hash");

                    b.ToTable("invitations", "catalog");
                });

            modelBuilder.Entity("ControlPlane.Domain.Roles.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BuiltIn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("built_in");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-7000-8000-000000000001"),
                            BuiltIn = "Owner",
                            Name = "Owner"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-7000-8000-000000000002"),
                            BuiltIn = "Admin",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-7000-8000-000000000003"),
                            BuiltIn = "Member",
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("ControlPlane.Domain.SystemAdmins.SystemAdmin", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid?>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.HasKey("UserId")
                        .HasName("pk_system_admins");

                    b.HasIndex("GrantedBy")
                        .HasDatabaseName("ix_system_admins_granted_by");

                    b.ToTable("system_admins", "catalog");
                });

            modelBuilder.Entity("ControlPlane.Domain.Tenants.Membership", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id")
                        .HasDefaultValueSql("NULLIF(current_setting('app.tenant_id', true), '')::uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("TenantId", "UserId")
                        .HasName("pk_memberships");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_memberships_role_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_memberships_user_id");

                    b.ToTable("memberships", "catalog");
                });

            modelBuilder.Entity("ControlPlane.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cancellation_reason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", "catalog");
                });

            modelBuilder.Entity("ControlPlane.Domain.Tenants.TenantCreationRequest", b =>
                {
                    b.Property<Guid>("SystemAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("system_admin_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("SystemAdminId", "IdempotencyKey")
                        .HasName("pk_tenant_creation_requests");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_tenant_creation_requests_tenant_id");

                    b.ToTable("tenant_creation_requests", "catalog");
                });

            modelBuilder.Entity("ControlPlane.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_external_id");

                    b.ToTable("users", "catalog");
                });

            modelBuilder.Entity("ControlPlane.Domain.Invitations.Invitation", b =>
                {
                    b.HasOne("ControlPlane.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AcceptedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invitations_users_accepted_by");

                    b.HasOne("ControlPlane.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_users_invited_by");

                    b.HasOne("ControlPlane.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_roles_role_id");

                    b.HasOne("ControlPlane.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_tenants_tenant_id");
                });

            modelBuilder.Entity("ControlPlane.Domain.SystemAdmins.SystemAdmin", b =>
                {
                    b.HasOne("ControlPlane.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("GrantedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_system_admins_users_granted_by");

                    b.HasOne("ControlPlane.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("ControlPlane.Domain.SystemAdmins.SystemAdmin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_system_admins_users_user_id");
                });

            modelBuilder.Entity("ControlPlane.Domain.Tenants.Membership", b =>
                {
                    b.HasOne("ControlPlane.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_roles_role_id");

                    b.HasOne("ControlPlane.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_tenants_tenant_id");

                    b.HasOne("ControlPlane.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_users_user_id");
                });

            modelBuilder.Entity("ControlPlane.Domain.Tenants.TenantCreationRequest", b =>
                {
                    b.HasOne("ControlPlane.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("SystemAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_creation_requests_users_system_admin_id");

                    b.HasOne("ControlPlane.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_creation_requests_tenants_tenant_id");
                });
#pragma warning restore 612, 618
        }
    }
}
