<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="Audit.Application" />
    <InternalsVisibleTo Include="Audit.Infrastructure" />
    <InternalsVisibleTo Include="Audit.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

</Project>
