<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <InternalsVisibleTo Include="ControlPlane.Application" />
    <InternalsVisibleTo Include="ControlPlane.Infrastructure" />
    <InternalsVisibleTo Include="ControlPlane.UnitTests" />
    <InternalsVisibleTo Include="ControlPlane.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

</Project>
